name: Build specific Docker image version

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      VERSION: 0.3.5
    steps:          
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S%:::z')"
        
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/arm/v7
          push: true
          tags: |            
            ghcr.io/bas-korver/jmusicbot:${{ env.VERSION }}            
#             bas0korver/jmusicbot:${{ env.VERSION }}
          build-args: |
            JMUSICBOT_VERSION=${{ env.VERSION }}
            BUILDDATE=${{ steps.date.outputs.date }}
