name: Generate

on:
  push:

jobs:
  generate:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the weg Git works, without it this action won't be able to find any or the correct tags
      - id: keydb
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: Bas-Korver
          repo: docker-jmusicbot
          excludes: prerelease, draft
