name: Publish Docker image

on:
  push:

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            bas0korver/jmusicbot
            ghcr.io/${{ github.repository }}
            
      - name: tags
        run: echo ${{ steps.meta.outputs.tags }}
        
      - name: labels
        run: echo ${{ steps.meta.outputs.labels }}
